insert into player(name) values ('Blue Heavy');
insert into player(name) values ('Red Heavy');
insert into player(name) values ('CakeSlayer');
insert into player(name) values ('Luri1337');
insert into player(name) values ('Dart Vader');
insert into player(name) values ('Finn the Human');
insert into player(name) values ('Serjan Bratan');
insert into player(name) values ('NoobMaster69');
insert into player(name) values ('Because I`m Batman');
insert into player(name) values ('mrvert');
insert into player(name) values ('Leviticus Cornwall');
insert into player(name) values ('Tarnished');
insert into player(name) values ('Aang The Avatar');
insert into player(name) values ('Marcus Aurelius');
insert into player(name) values ('King Arthur');
insert into player(name) values ('Nivellen');
insert into player(name) values ('Strange Man');
insert into player(name) values ('Amanda`s lover');
insert into player(name) values ('Torin Oakenshield');
insert into player(name) values ('Serana');

insert into match(first_player_id, second_player_id, winner_id) values (1,2,1);
insert into match(first_player_id, second_player_id, winner_id) values (3,4,3);
insert into match(first_player_id, second_player_id, winner_id) values (5,8,5);
insert into match(first_player_id, second_player_id, winner_id) values (9,14,14);
insert into match(first_player_id, second_player_id, winner_id) values (13,18,13);
insert into match(first_player_id, second_player_id, winner_id) values (10,17,10);
insert into match(first_player_id, second_player_id, winner_id) values (12,7,7);
insert into match(first_player_id, second_player_id, winner_id) values (19,6,6);
insert into match(first_player_id, second_player_id, winner_id) values (15,16,16);
insert into match(first_player_id, second_player_id, winner_id) values (20,3,20);
insert into match(first_player_id, second_player_id, winner_id) values (4,16,4);
insert into match(first_player_id, second_player_id, winner_id) values (18,1,1);
insert into match(first_player_id, second_player_id, winner_id) values (19,15,19);
insert into match(first_player_id, second_player_id, winner_id) values (17,11,17);
insert into match(first_player_id, second_player_id, winner_id) values (14,8,14);
insert into match(first_player_id, second_player_id, winner_id) values (10,9,9);
insert into match(first_player_id, second_player_id, winner_id) values (12,5,5);
insert into match(first_player_id, second_player_id, winner_id) values (13,20,13);
insert into match(first_player_id, second_player_id, winner_id) values (18,11,18);
insert into match(first_player_id, second_player_id, winner_id) values (3,10,10);
